apiVersion: v1
kind: ConfigMap
metadata:
  name: scraper-config
  namespace: default
data:
  cities: "Москва,Санкт-Петербург,Екатеринбург"
  cian_cooldown: "10"
  domclick_cooldown: "8"
  avito_cooldown: "15"
  yandex_cooldown: "8"
  shallow_url_dict: | 
    {
      "cian_sale_Москва": "https://www.cian.ru/cat.php?currency=2&deal_type=sale&engine_version=2&maxprice=8000000&minprice=100000&offer_type=flat&p=2&region=1&sort=price_object_order",
      "cian_sale_Санкт-Петербург": "https://spb.cian.ru/cat.php?currency=2&deal_type=sale&engine_version=2&maxprice=8000000&minprice=100000&offer_type=flat&p=2&region=2&sort=price_object_order",
      "cian_sale_Екатеринбург": "https://ekb.cian.ru/cat.php?currency=2&deal_type=sale&engine_version=2&maxprice=8000000&minprice=100000&offer_type=flat&p=2&region=4743&sort=price_object_order",
      "cian_rent_Москва": "https://www.cian.ru/cat.php?currency=2&deal_type=rent&engine_version=2&maxprice=100000&minprice=10000&offer_type=flat&p=2&region=1&sort=price_object_order&type=4",
      "cian_rent_Санкт-Петербург": "https://spb.cian.ru/cat.php?currency=2&deal_type=rent&engine_version=2&maxprice=100000&minprice=10000&offer_type=flat&p=2&region=2&sort=price_object_order&type=4",
      "cian_rent_Екатеринбург": "https://ekb.cian.ru/cat.php?currency=2&deal_type=rent&engine_version=2&maxprice=100000&minprice=10000&offer_type=flat&p=2&region=4743&sort=price_object_order&type=4",
      "domclick_sale_Москва": "https://domclick.ru/search?deal_type=sale&category=living&offer_type=flat&offer_type=layout&sale_price__gte=2000000&sort=price&sort_dir=asc&offset=0",
      "domclick_sale_Санкт-Петербург": "https://spb.domclick.ru/search?deal_type=sale&category=living&offer_type=flat&offer_type=layout&sale_price__gte=2000000&sort=price&sort_dir=asc&offset=0",
      "domclick_sale_Екатеринбург": "https://ekaterinburg.domclick.ru/search?deal_type=sale&category=living&offer_type=flat&offer_type=layout&sale_price__gte=2000000&sort=price&sort_dir=asc&offset=0",
      "domclick_rent_Москва": "https://domclick.ru/search?deal_type=rent&category=living&offer_type=flat&offer_type=layout&rent_price__gte=10000&sort=price&sort_dir=asc&offset=0",
      "domclick_rent_Санкт-Петербург": "https://spb.domclick.ru/search?deal_type=rent&category=living&offer_type=flat&offer_type=layout&rent_price__gte=10000&sort=price&sort_dir=asc&offset=0",
      "domclick_rent_Екатеринбург": "https://ekaterinburg.domclick.ru/search?deal_type=rent&category=living&offer_type=flat&offer_type=layout&rent_price__gte=10000&sort=price&sort_dir=asc&offset=0",
      "avito_sale_Москва": "https://www.avito.ru/moskva/kvartiry/prodam?bt=1&params[120711]=1&pmin=100000&p=1&s=1",
      "avito_sale_Санкт-Петербург": "https://www.avito.ru/sankt-peterburg/kvartiry/prodam?bt=1&pmin=100000&p=1&s=1",
      "avito_sale_Екатеринбург": "https://www.avito.ru/ekaterinburg/kvartiry/prodam?bt=1&pmin=100000&p=1&s=1",
      "avito_rent_Москва": "https://www.avito.ru/moskva/kvartiry/sdam/na_dlitelnyy_srok?bt=1&pmin=10000&p=1&s=1",
      "avito_rent_Санкт-Петербург": "https://www.avito.ru/sankt-peterburg/kvartiry/sdam/na_dlitelnyy_srok?bt=1&pmin=10000&p=1&s=1",
      "avito_rent_Екатеринбург": "https://www.avito.ru/ekaterinburg/kvartiry/sdam/na_dlitelnyy_srok?bt=1&pmin=10000&p=1&s=1",
      "yandex_sale_Москва": "https://realty.ya.ru/moskva/kupit/kvartira/?sort=PRICE&priceMin=1000000&showSimilar=NO&page=1",
      "yandex_sale_Санкт-Петербург": "https://realty.ya.ru/sankt-peterburg/kupit/kvartira/?sort=PRICE&priceMin=1000000&showSimilar=NO&page=1",
      "yandex_sale_Екатеринбург": "https://realty.ya.ru/ekaterinburg/kupit/kvartira/?sort=PRICE&priceMin=1000000&showSimilar=NO&page=1",
      "yandex_rent_Москва": "https://realty.ya.ru/moskva/snyat/kvartira/?sort=PRICE&priceMin=10000&showSimilar=NO&page=1",
      "yandex_rent_Санкт-Петербург": "https://realty.ya.ru/sankt-peterburg/snyat/kvartira/?sort=PRICE&priceMin=10000&showSimilar=NO&page=1",
      "yandex_rent_Екатеринбург": "https://realty.ya.ru/ekaterinburg/snyat/kvartira/?sort=PRICE&priceMin=10000&showSimilar=NO&page=1"
    }
  deep_url_dict: |
    {
      "cian_sale_Москва": "15,https://www.cian.ru/cat.php?deal_type=sale&engine_version=2&offer_type=flat&p=2&region=1&sort=creation_date_desc",
      "cian_sale_Санкт-Петербург": "30,https://spb.cian.ru/cat.php?deal_type=sale&engine_version=2&offer_type=flat&p=2&region=2&sort=creation_date_desc",
      "cian_sale_Екатеринбург": "60,https://ekb.cian.ru/cat.php?deal_type=sale&engine_version=2&offer_type=flat&p=2&region=4743&sort=creation_date_desc",
      "cian_sale": "cian.ru/sale/flat"
    }