apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-getaway-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: api-getaway-app
  template:
    metadata:
      labels:
        app: api-getaway-app
    spec:
      containers:
      - name: api-getaway
        image: stikeyrs/scraper:api_getaway_chrome_driver
        ports:
          - containerPort: 8083
        livenessProbe:
          httpGet:
            path: /ping  # Путь, который будет использоваться для проверки "живости" контейнера
            port: 8083  # Порт, на котором работает ваше приложение
          initialDelaySeconds: 120  # Задержка перед первой проверкой (в секундах)
          periodSeconds: 120  # Периодичность проверок "живости" (в секундах)
          failureThreshold: 5  # Количество неудачных проверок перед перезапуском
      imagePullSecrets:
        - name: docker-registry-secret
