apiVersion: batch/v1
kind: CronJob
metadata:
  name: parsers-cronjob
spec:
  schedule: "*/60 * * * *"  # Расписание Cron (запуск каждые 60 минут)
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: shallow-sale-parser-cian-moskow
            image: stikeyrs/scraper:shallow_sale_parser
            env:
              - name: WEBSITE_NAME
                value: cian
              - name: CITY
                value: Москва
          restartPolicy: OnFailure  # Политика перезапуска контейнера
          imagePullSecrets:
            - name: docker-registry-secret