apiVersion: apps/v1
kind: Deployment
metadata:
  name: parser
  namespace: default
spec:
  selector:
    matchLabels:
      app: parser
  template:
    metadata:
      labels:
        app: parser
    spec:
#      containers:
#        - name: shallow-sale-parser-cian-moskow
#          image: stikeyrs/scraper:parser
#          env:
#            - name: WEBSITE_NAME
#              value: cian
#            - name: TYPE
#              value: rent
#            - name: MODE
#              value: shallow
#        - name: shallow-sale-parser-domclick-moskow
#          image: stikeyrs/scraper:parser
#          env:
#            - name: WEBSITE_NAME
#              value: domclick
#            - name: TYPE
#              value: rent
#            - name: MODE
#              value: shallow
#        - name: shallow-sale-parser-avito-moskow
#          image: stikeyrs/scraper:parser
#          env:
#            - name: WEBSITE_NAME
#              value: avito
#            - name: TYPE
#              value: rent
#            - name: MODE
#              value: shallow
#        - name: shallow-sale-parser-yandex-moskow
#          image: stikeyrs/scraper:parser
#          env:
#            - name: WEBSITE_NAME
#              value: yandex
#            - name: TYPE
#              value: rent
#            - name: MODE
#              value: shallow
      containers:
        - name: deep-sale-parser-cian
          image: stikeyrs/scraper:parser
          env:
            - name: WEBSITE_NAME
              value: cian
            - name: TYPE
              value: sale
            - name: MODE
              value: deep
        - name: deep-sale-parser-avito
          image: stikeyrs/scraper:parser
          env:
            - name: WEBSITE_NAME
              value: avito
            - name: TYPE
              value: sale
            - name: MODE
              value: deep
        - name: deep-sale-parser-domclick
          image: stikeyrs/scraper:parser
          env:
            - name: WEBSITE_NAME
              value: domclick
            - name: TYPE
              value: sale
            - name: MODE
              value: deep
#        - name: deep-sale-parser-yandex
#          image: stikeyrs/scraper:parser
#          env:
#            - name: WEBSITE_NAME
#              value: yandex
#            - name: TYPE
#              value: sale
#            - name: MODE
#              value: deep
#      restartPolicy: OnFailure  # Политика перезапуска контейнера
      imagePullSecrets:
        - name: docker-registry-secret