apiVersion: apps/v1
kind: Deployment
metadata:
  name: chrome-driver-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chrome-driver-app
  template:
    metadata:
      labels:
        app: chrome-driver-app
    spec:
      containers:
      - name: container
        image: stikeyrs/scraper:driver-container
        resources:
          limits:
            cpu: "0.7"
            memory: "700Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
        ports:
          - containerPort: 8082
        livenessProbe:
          httpGet:
            path: /ping  # Путь, который будет использоваться для проверки "живости" контейнера
            port: 8082  # Порт, на котором работает ваше приложение
          initialDelaySeconds: 30  # Задержка перед первой проверкой (в секундах)
          periodSeconds: 60  # Периодичность проверок "живости" (в секундах)
          failureThreshold: 5  # Количество неудачных проверок перед перезапуском
      imagePullSecrets:
        - name: docker-registry-secret
