apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-api-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: db-api-app
  template:
    metadata:
      labels:
        app: db-api-app
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: 1242241к
            - name: POSTGRES_DB
              value: realestatedb
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
        - name: db-api
          image: stikeyrs/scraper:db-api
          resources:
            requests:
              memory: "100Mi"
            limits:
              memory: "500Mi"
          volumeMounts:
            - name: images-storage
              mountPath: /app/images
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /ping  # Путь, который будет использоваться для проверки "живости" контейнера
              port: 8080  # Порт, на котором работает ваше приложение
            initialDelaySeconds: 120  # Задержка перед первой проверкой (в секундах)
            periodSeconds: 120  # Периодичность проверок "живости" (в секундах)
            failureThreshold: 5  # Количество неудачных проверок перед перезапуском
#      imagePullSecrets:
#        - name: docker-registry-secret
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
      - name: images-storage
        persistentVolumeClaim:
          claimName: images-pvc